# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.2
minecraft_version_range=[1.20.2,1.20.3)

# Forge
forge_id=forge
forge_version=48.1.0
forge_version_range=[48,)

mapping_channel=official
mapping_version=1.20.2

# NeoForge
neoforge_id=neoforge
neogradle.subsystems.parchment.minecraftVersion=1.20.2
neogradle.subsystems.parchment.mappingsVersion=2023.12.10
neo_version=20.2.93
neo_version_range=[20.2,)
neo_loader_version_range=[1,)

# Mod
mod_group_id=xiao.battleroyale
mod_id=battleroyale
mod_name=Custom BattleRoyale
mod_license=GPL-3.0 license
mod_version=0.5.3-dev2
mod_credits=XiaoColorful, XColorful
mod_authors=XiaoColorful
mod_description=Play customizable battleroyale in Minecraft

mod_issue_url=https://github.com/XColorful/BattleRoyale/issues
mod_display_url=https://github.com/XColorful/BattleRoyale/wiki
mod_logo_file=logo.png

pack_description=CBR resources
pack_format=15

# Dependencies
journeymap_version_range=[5.9.0,)
playerrevive_version_range=[2.0.16,]
tacz_version_range=[1.0.2,]
cbraddon_version_range=[0.4.4-dev3,)
armorscaling_version_range=[0.5.1,)

journeymap_api_version=1.20-1.9-SNAPSHOT
journeymap_neoforge_api_version=1.20.2-1.9-neoforge-SNAPSHOT

# CompileOnly
# journeymap-1.20.2-5.9.21-forge.jar
journeymap_curse_maven=curse.maven:journeymap-32274:5293045
# journeymap-1.20.2-5.9.22-neoforge.jar
journeymap_neoforge_curse_maven=curse.maven:journeymap-32274:5388275