# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.21.5)

# Forge
forge_id=forge
forge_version=52.1.10
forge_version_range=[52,)

mapping_channel=official
mapping_version=1.21.4

# NeoForge
neoforge_id=neoforge
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23
neo_version=21.4.156
neo_version_range=[21,)
neo_loader_version_range=[1,)

# Mod
mod_group_id=xiao.battleroyale
mod_id=battleroyale
mod_name=Custom BattleRoyale
mod_license=GPL-3.0 license
mod_version=0.5.2
mod_credits=XiaoColorful, XColorful
mod_authors=XiaoColorful
mod_description=Play customizable battleroyale in Minecraft

mod_issue_url=https://github.com/XColorful/BattleRoyale/issues
mod_display_url=https://github.com/XColorful/BattleRoyale/wiki
mod_logo_file=logo.png

pack_description=CBR resources
pack_format=15

# Dependencies
journeymap_version_range=[1.21-6.0.0-beta.1,)
playerrevive_version_range=[2.0.16,]
tacz_version_range=[1.0.2,]
cbraddon_version_range=[0.4.4-dev3,)
armorscaling_version_range=[0.5.1,)

journeymap_api_version=2.0.0-1.21.1-SNAPSHOT
journeymap_neoforge_api_version=2.0.0-1.21.4-SNAPSHOT

# CompileOnly
# journeymap-forge-1.21.1-6.0.0-beta.52.jar
journeymap_curse_maven=curse.maven:journeymap-32274:6689204
# journeymap-neoforge-1.21.4-6.0.0-beta.47.jar
journeymap_neoforge_curse_maven=curse.maven:journeymap-32274:6550384