modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/XColorful/BattleRoyale/issues"

[[mods]]
modId="battleroyale"
version="${mod_version}"
displayName="Custom BattleRoyale"
displayURL="https://github.com/XColorful/BattleRoyale/wiki"
logoFile="logo.png"
authors="XiaoColorful"
description='''Play customizable battleroyale in Minecraft
'''

[[dependencies.battleroyale]]
    modId="${target_modloader}"
    mandatory=true
    versionRange="${target_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.battleroyale]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.battleroyale]]
    modId = "journeymap"
    mandatory = false
    versionRange = "[5.9.0,)"
    ordering = "NONE"
    side = "CLIENT"
[[dependencies.battleroyale]]
    modId="playerrevive"
    mandatory=false
    versionRange="[2.0.16,]"
    side="BOTH"
[[dependencies.battleroyale]]
    modId="tacz"
    mandatory=false
    versionRange="[1.0.2,]"
    side="BOTH"