modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/XColorful/BattleRoyale/issues"

[[mods]]
modId="battleroyale"
version="${mod_version}"
displayName="Custom BattleRoyale"
displayURL="https://github.com/XColorful/BattleRoyale/wiki"
logoFile="logo.png"
authors="XiaoColorful"
description='''
'''

[[dependencies.battleroyale]]
    modId="${target_modloader}"
    type="required"
    versionRange="${target_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.battleroyale]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.battleroyale]]
    modId = "journeymap"
    type="optional"
    versionRange = "[1.21-6.0.0-beta.1,)"
    ordering = "NONE"
    side = "CLIENT"
[[dependencies.battleroyale]]
    modId="playerrevive"
    type="optional"
    versionRange="[2.0.16,]"
    side="BOTH"
[[dependencies.battleroyale]]
    modId="tacz"
    type="optional"
    versionRange="[1.0.2,]"
    side="BOTH"