plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

loom {
    accessWidenerPath = file("src/main/resources/battleroyale.accesswidener")
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
}

jar {
    archiveBaseName.set(mod_id)
    archiveVersion.set(mod_version)
    archiveClassifier.set("core")
}