package xiao.battleroyale.api.event;

public enum CustomEventType {
    // finish
    GAME_COMPLETE_EVENT,
    GAME_COMPLETE_FINISH_EVENT,
    GAME_STOP_EVENT,
    GAME_STOP_FINISH_EVENT,
    SERVER_STOP_EVENT,
    SERVER_STOP_FINISH_EVENT,
    // game
    GAME_PLAYER_DEATH_EVENT,
    GAME_PLAYER_DEATH_FINISH_EVENT,
    GAME_PLAYER_DOWN_EVENT,
    GAME_PLAYER_DOWN_FINISH_EVENT,
    GAME_PLAYER_REVIVE_EVENT,
    GAME_PLAYER_REVIVE_FINISH_EVENT,
    GAME_SPECTATE_EVENT,
    // spawn
    GAME_LOBBY_TELEPORT_EVENT,
    GAME_LOBBY_TELEPORT_FINISH_EVENT,
    // starter
    GAME_INIT_EVENT,
    GAME_INIT_FINISH_EVENT,
    GAME_LOAD_EVENT,
    GAME_LOAD_FINISH_EVENT,
    GAME_START_EVENT,
    GAME_START_FINISH_EVENT,
    // team,
    INVITE_PLAYER_EVENT,
    INVITE_PLAYER_COMPLETE_EVENT,
    REQUEST_PLAYER_EVENT,
    REQUEST_PLAYER_COMPLETE_EVENT,
    // tick
    GAME_LOOT_BFS_EVENT,
    GAME_LOOT_BFS_FINISH_EVENT,
    GAME_LOOT_EVENT,
    GAME_LOOT_FINISH_EVENT,
    GAME_TICK_EVENT,
    GAME_TICK_FINISH_EVENT,
    ZONE_TICK_EVENT,
    ZONE_TICK_FINISH_EVENT,
    // zone
    AIRDROP_EVENT,
    CUSTOM_ZONE_EVENT,
    ZONE_COMPLETE_EVENT,
    ZONE_CREATED_EVENT
}
