package xiao.battleroyale.api.event;

public enum EventType {
    SERVER_TICK_EVENT,
    CLIENT_TICK_EVENT,
    LIVING_ATTACK_EVENT,
    LIVING_HURT_EVENT,
    LIVING_DAMAGE_EVENT,
    LIVING_DEATH_EVENT,
    PLAYER_LOGGED_IN_EVENT,
    PLAYER_LOGGED_OUT_EVENT,
    RENDER_LEVEL_STAGE_EVENT,
    RENDER_TRANSLUCENT_EVENT, // 单独拆一个事件，避免多次上锁，减少一点不必要的开销
    RENDER_GUI_EVENT
}
